;; Reads config.json and generates two nginx include files:
;;   nginx/upstreams.conf  — one upstream{} block per service  (http context)
;;   nginx/locations.conf  — one location block per service    (server context)
;;
;; Run before starting nginx:
;;   luajit generate.lua        (Docker / OpenResty luajit)
;;   lua generate.lua           (dev, requires dkjson)
;;
;; Services with tls.cert/key get proxy_ssl_certificate directives and
;; proxy_pass over https://. Services whose upstream URL starts with https://
;; but have no client cert get proxy_ssl_verify only.
;;
;; Regex locations (~ ^/name(/|$)) enforce the slash boundary so /users
;; does not match /userssettings. Longer names are emitted first so
;; /users-v2 is checked before /users.

(local json
  (let [(ok m) (pcall require :cjson)]
    (if ok m (require :dkjson))))

(fn read-file [path]
  (let [f (assert (io.open path :r) (.. "cannot open: " path))
        data (f:read :*a)]
    (f:close)
    data))

(fn validate-name [name]
  (assert (name:match "^[a-zA-Z0-9_-]+$")
          (.. "invalid service name: '" name "' — only [a-zA-Z0-9_-] allowed")))

(fn upstream-addr [url]
  (or (url:match "^https?://([^/]+)") url))

(fn use-https? [svc]
  (or (not= nil (svc.upstream:match "^https://"))
      (and svc.tls (or svc.tls.cert svc.tls.key))))

(fn emit-upstream [svc buf]
  (table.insert buf (.. "upstream " svc.name "_upstream {\n"))
  (table.insert buf (.. "    server " (upstream-addr svc.upstream) ";\n"))
  (table.insert buf     "    keepalive 32;\n")
  (table.insert buf     "    keepalive_requests 1000;\n")
  (table.insert buf     "    keepalive_timeout 60s;\n")
  (table.insert buf "}\n\n"))

(fn emit-location [svc buf]
  (let [https (use-https? svc)
        scheme (if https "https" "http")
        timeout-s (math.max 1 (math.ceil (/ (or svc.timeout 30000) 1000)))
        host-hdr (upstream-addr svc.upstream)]
    (table.insert buf (.. "location ~ ^/" svc.name "(/|$) {\n"))
    (table.insert buf (.. "    set $svc_name             \"" svc.name "\";\n"))
    (table.insert buf (.. "    set $upstream_host_header \"" host-hdr "\";\n"))
    (when https
      (when (and svc.tls svc.tls.cert)
        (table.insert buf (.. "    proxy_ssl_certificate     " svc.tls.cert ";\n")))
      (when (and svc.tls svc.tls.key)
        (table.insert buf (.. "    proxy_ssl_certificate_key " svc.tls.key ";\n")))
      (let [verify (and svc.tls svc.tls.verify)]
        (table.insert buf (.. "    proxy_ssl_verify          " (if verify "on" "off") ";\n"))))
    (table.insert buf (.. "    proxy_connect_timeout     " timeout-s "s;\n"))
    (table.insert buf (.. "    proxy_read_timeout        " timeout-s "s;\n"))
    (table.insert buf (.. "    proxy_send_timeout        " timeout-s "s;\n"))
    (when svc.nginx_directives
      (each [_ directive (ipairs svc.nginx_directives)]
        (table.insert buf (.. "    " directive ";\n"))))
    (table.insert buf     "    access_by_lua_block        { require(\"router\").access() }\n")
    (table.insert buf     "    header_filter_by_lua_block { require(\"router\").on_response() }\n")
    (table.insert buf     "    log_by_lua_block           { require(\"router\").log() }\n")
    (table.insert buf (.. "    proxy_pass                 " scheme "://" svc.name "_upstream$upstream_path;\n"))
    (table.insert buf "}\n\n")))

(let [cfg (json.decode (read-file "config.json"))
      svcs cfg.services
      ;; Longer service names first so overlapping prefixes match correctly.
      _ (table.sort svcs (fn [a b] (> (# a.name) (# b.name))))
      up-buf  ["# Auto-generated by generate.fnl — do not edit\n\n"]
      loc-buf ["# Auto-generated by generate.fnl — do not edit\n\n"]]
  (each [_ svc (ipairs svcs)]
    (validate-name svc.name)
    (emit-upstream svc up-buf)
    (emit-location svc loc-buf))
  (let [uf (assert (io.open "nginx/upstreams.conf" "w"))]
    (uf:write (table.concat up-buf))
    (uf:close))
  (let [lf (assert (io.open "nginx/locations.conf" "w"))]
    (lf:write (table.concat loc-buf))
    (lf:close))
  (io.write (.. "generated nginx/upstreams.conf + nginx/locations.conf"
                " for " (# svcs) " service(s)\n")))
